steps:
  - name: ":python: :buildkite: :sweat_smile:"
    command: "python upload.py"
    plugins:
      - docker-compose#v3.7.0:
          run: app
          propagate-environment: true
          environment:
            - "hostname=<<replace_env>>"
            - ASCEND_ACCESS_KEY
            - ASCEND_SECRET_KEY
